import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api } from '../api';
import type { AnalysisFunctionKind } from '../types';
export function AnalysisFunctionsPage() {
  const queryClient = useQueryClient(); const navigate = useNavigate(); const functions = useQuery({ queryKey: ['analysis-functions'], queryFn: api.listAnalysisFunctions });
  const [name, setName] = useState(''); const [key, setKey] = useState(''); const [kind, setKind] = useState<AnalysisFunctionKind>('point-map');
  const create = useMutation({ mutationFn: () => api.createAnalysisFunction({ name, functionKey: key, functionKind: kind }), onSuccess: (item) => { void queryClient.invalidateQueries({ queryKey: ['analysis-functions'] }); navigate(`/analysis-functions/${item.id}`); } });
  return <div className="analysis-list-page"><header><div><h1>Analysis functions</h1><p>Versioned functions that can be pinned by visual pipelines and code-mode programs.</p></div></header><section className="analysis-panel"><h2>Create function</h2><form className="analysis-create-row" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><input placeholder="Name" value={name} onChange={(event) => { setName(event.target.value); if (!key) setKey(event.target.value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')); }} required /><input placeholder="stable-key" value={key} onChange={(event) => setKey(event.target.value)} required /><select value={kind} onChange={(event) => setKind(event.target.value as AnalysisFunctionKind)}><option value="event-filter">Event filter</option><option value="point-map">Point map</option><option value="point-filter">Point filter</option><option value="map-filter">Map/filter</option><option value="window-transform">Window transform</option><option value="reducer">Reducer</option><option value="series-transform">Series transform</option></select><button type="submit" disabled={create.isPending}>Create</button></form></section><section className="analysis-function-grid">{(functions.data ?? []).map((item) => <Link className="analysis-function-card" key={item.id} to={`/analysis-functions/${item.id}`}><header><strong>{item.name}</strong>{item.is_system && <span>System</span>}</header><code>{item.function_key}</code><p>{item.description ?? 'No description'}</p><footer><span>{item.function_kind}</span><span>{item.published_revision_id ? 'Published' : item.draft_revision_id ? item.draft_validation_status : 'No revision'}</span></footer></Link>)}</section></div>;
}
