import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { analysisFunctionIdentifier, type AnalysisFunctionKind, type AnalysisValidationReport, type SourceDiagnostic } from '@logbook/analysis-sdk';
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../api';
import { AnalysisFunctionEditor } from '@logbook/analysis-editor';
import { ValidationReport } from '../analysis/validation/ValidationReport';
const templates: Record<AnalysisFunctionKind, string> = {
  'event-filter': 'return event.inRequestedRange;', 'point-map': 'return value;', 'point-filter': 'return value !== null;',
  'map-filter': 'return value === null ? MapFilterResult.drop() : MapFilterResult.keep(value);',
  'window-transform': 'const values = window.validValues();\nreturn values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null;',
  reducer: 'const valid = values.filter((value) => value !== null);\nreturn valid.length ? valid.reduce((sum, value) => sum + value, 0) / valid.length : null;',
  'series-transform': 'return series;'
};
export function AnalysisFunctionPage() {
  const { functionId = '' } = useParams(); const queryClient = useQueryClient(); const detail = useQuery({ queryKey: ['analysis-function', functionId], queryFn: () => api.getAnalysisFunction(functionId), enabled: Boolean(functionId), refetchInterval: false });
  const [source, setSource] = useState('return value;'); const [typeDiagnostics, setTypeDiagnostics] = useState<SourceDiagnostic[]>([]); const [report, setReport] = useState<AnalysisValidationReport | null>(null); const [revisionId, setRevisionId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const item = detail.data as { name?: string; function_key?: string; function_kind?: AnalysisFunctionKind; description?: string; is_system?: boolean; published_revision_id?: string | null; revisions?: Array<{ id: string; source_body: string; validation_report?: AnalysisValidationReport; validation_status?: string; revision?: number }> } | undefined;
  useEffect(() => { if (!item) return; const revision = item.revisions?.[0]; setSource(revision?.source_body ?? templates[item.function_kind ?? 'point-map']); setRevisionId(revision?.id ?? null); setReport(revision?.validation_report ?? null); }, [detail.data]);
  const save = useMutation({ mutationFn: () => api.createAnalysisFunctionRevision(functionId, { alias: analysisFunctionIdentifier(item?.function_key ?? 'udf'), functionKind: item?.function_kind ?? 'point-map', sourceBody: source, parameterSchema: { type: 'object', additionalProperties: true }, defaultOptions: {}, outputMetadata: {} }), onSuccess: (revision) => { setRevisionId(String(revision.id)); setReport(revision.validationReport as AnalysisValidationReport); setError(null); void Promise.all([queryClient.invalidateQueries({ queryKey: ['analysis-function', functionId] }), queryClient.invalidateQueries({ queryKey: ['analysis-functions'] })]); }, onError: (value) => setError(value instanceof Error ? value.message : String(value)) });
  const publish = useMutation({ mutationFn: () => { if (!revisionId) throw new Error('Save a revision first'); return api.publishAnalysisFunctionRevision(functionId, revisionId); }, onSuccess: () => void Promise.all([queryClient.invalidateQueries({ queryKey: ['analysis-function', functionId] }), queryClient.invalidateQueries({ queryKey: ['analysis-functions'] })]), onError: (value) => setError(value instanceof Error ? value.message : String(value)) });
  if (detail.isLoading) return <p>Loading function…</p>; if (!item) return <p>Function not found.</p>;
  return <div className="analysis-function-page"><header className="analysis-toolbar"><div><Link to="/analysis-functions">← Functions</Link><h1>{item.name}</h1><code>{item.function_key}</code><p>{item.description}</p></div><div className="analysis-toolbar-actions"><span>{item.function_kind}</span>{item.is_system && <span>System</span>}<button type="button" onClick={() => save.mutate()} disabled={save.isPending || item.is_system || typeDiagnostics.some((diagnostic) => diagnostic.severity === 'error')}>Save revision</button><button type="button" onClick={() => publish.mutate()} disabled={publish.isPending || report?.status !== 'passed' || item.is_system}>Publish</button></div></header>{error && <div className="analysis-error">{error}</div>}<div className="analysis-layout single"><main><section className="analysis-panel"><h2>Function body</h2><p className="analysis-signature">{item.function_kind === 'point-map' ? 'function(value, point, index, options, context)' : item.function_kind === 'window-transform' ? 'function(window, options, context)' : item.function_kind === 'reducer' ? 'function(values, points, options, context)' : `function(/* ${item.function_kind} arguments */)`}</p><AnalysisFunctionEditor sourceBody={source} onSourceBodyChange={setSource} readOnly={Boolean(item.is_system)} functionKind={item.function_kind ?? 'point-map'} functionAlias={analysisFunctionIdentifier(item.function_key ?? 'udf')} onTypeDiagnosticsChange={setTypeDiagnostics} modelKey={`function-${functionId}`} onSaveShortcut={() => { if (!save.isPending && !item.is_system && !typeDiagnostics.some((diagnostic) => diagnostic.severity === 'error')) save.mutate(); }} /></section><section className="analysis-panel"><h2>Validation</h2><ValidationReport report={report} /></section></main></div></div>;
}
